### ISSUE TITLE
App suddenly not working

### ISSUE THREAD

**Issue by shaundai** [peakchen90/vscode-open-in-default-browser#11]
I haven't made any updates to my computer, but my app is no longer working in VSCode (started yesterday).  If I try to Command+1 from my mac or right-click and select Open In Default Browser, I get the following error message: An error occurred opening the browser. Please restart VSCODE and try again! Source: Open in Default Browser (extension)

**Comment by peakchen90** [comment]
@shaundai  Maybe your workspace folder is updated, please try restarting VSCode.
