### ISSUE TITLE
打开文件的时候加上自定义服务器地址

### ISSUE THREAD

**Issue by sochishun** [peakchen90/vscode-open-in-default-browser#14]
NetBeans有一个功能，就是可以配置项目服务器URL，然后点击“在浏览器打开”的时候，直接就是服务器路径的文件地址，比如配置服务器路径为：http://localhost:8080，那打开项目中/public/index.php的时候，地址就变成：http://localhost:8080/public/index.php，这样在开发项目时很有用。

**Comment by peakchen90** [comment]
这个插件的定位在于简单、开箱即用，所以目前暂时不考虑新增额外的配置来支持自定义行为
