### ISSUE TITLE
Define or remove https://service.peakchen.cn from Source code

### ISSUE THREAD

**Issue by crossan007** [peakchen90/vscode-open-in-default-browser#27]
Please define or explain why there is a URL hardcoded into this plugin.

Does it make any remote calls or "phone home"?

It looks to be unused in the code, so maybe it's just a development artifact?

**Comment by peakchen90** [comment]
This server address has long been used to count user languages for multilingual translation. But the service was later removed. It was removed about 2 years ago because some users were more sensitive about sending this data to the stats server, well that's it.
