### ISSUE TITLE
does not open anything.

### ISSUE THREAD

**Issue by carlosen14** [peakchen90/vscode-open-in-default-browser#5]
clicked on editor to open on default browser (ctrl + 1) but nothing happens, neither on file manager.

VSCODE
Version: 1.32.0
Commit: 507312a3e3b34b084b467dfd983263bc7c9d87e0
Date: 2019-03-06T18:53:01.021Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-16-generic

**Comment by peakchen90** [comment]
@carlosen14 
It can only open html files, please check if your file extension is `.html`

**Comment by carlosen14** [comment]
mmm, okey, i was trying to render a `.html` file, but this was a Angular based, the file was actually missing the `<html>`, `<head>` and `<body>` tags, only had a few body internal elements. Are these tags required?

**Comment by peakchen90** [comment]
@attackfrog 
I tried according to your description, but it can work.

VSCODE: 1.32.3
OS: MacOS 10.14.2

![image](https://user-images.githubusercontent.com/17677589/54967688-14e80100-4fb3-11e9-9b9f-f9863e77052d.png)

**Comment by mrpiggy97** [comment]
my file has a .html extension and vscode still won't open it, i have version 1.2.0 of the openhtml

**Comment by peakchen90** [comment]
@mrpiggy97 Please check if the shortcuts are conflicting, or try using the "open in default browser" menu.

**Comment by jondoe1337** [comment]
Same here under xubuntu with vscode 1.34.0 - however working under osx. :-/

**Comment by fuunnyy** [comment]
Only remind me reboot vscode, file extension is .html . now I'm very dazing

**Comment by peakchen90** [comment]
@fuunnyy This is caused by the internal mechanism. It may be that your editor workspace structure has been modified. Restarting it once should be fine. It would be better if a recurrence step could be provided.

**Comment by peakchen90** [comment]
It may not be a temporary file before, it has been fixed.
